import json
import os
import re

from ..state import MedicalReportState

_REVIEW_PROMPT = """You are a senior medical reviewer using NVIDIA Nemotron. Your job is to independently verify and critique the specialist analyses below that were generated by another AI system.

Original Patient Report:
{report}

Specialist Analyses (generated by Gemini AI):
{analyses}

Review these analyses critically and return ONLY valid JSON (no markdown):
{{
  "review_status": "approved",
  "confidence_score": 0.92,
  "agreements": [
    "Finding you agree with and why"
  ],
  "disagreements": [
    "Finding you disagree with or think is incorrect"
  ],
  "missed_findings": [
    "Important finding the specialists missed"
  ],
  "overall_urgency": "routine",
  "overall_summary": "Your independent consolidated summary for the treating physician",
  "reviewed_by": "NVIDIA Nemotron Reviewer"
}}

review_status: "approved" | "approved_with_notes" | "requires_re_evaluation"
overall_urgency:   "routine" | "urgent" | "critical"
confidence_score:  0.0 – 1.0
"""


def reviewer_node(state: MedicalReportState) -> dict:
    try:
        from openai import OpenAI

        client = OpenAI(
            base_url="https://integrate.api.nvidia.com/v1",
            api_key=os.environ.get("NVIDIA_API_KEY", ""),
        )
        model = os.environ.get("NVIDIA_MODEL", "nvidia/nemotron-3-8b-chat-sft-rlhf")

        analyses_json = json.dumps(state.get("specialist_analyses", []), indent=2)
        prompt = _REVIEW_PROMPT.format(
            report=state["patient_report_text"][:6000],
            analyses=analyses_json,
        )

        response = client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": "You are a senior medical reviewer. Be critical, thorough, and objective."},
                {"role": "user", "content": prompt},
            ],
            max_tokens=2048,
        )

        raw = response.choices[0].message.content.strip()
        m = re.search(r"\{.*\}", raw, re.DOTALL)
        if m:
            raw = m.group()

        review = json.loads(raw)
        return {"nvidia_review": review, "nvidia_review_success": True}

    except Exception as e:
        msg = f"NVIDIA reviewer unavailable: {type(e).__name__}: {e}"
        return {
            "nvidia_review": {
                "review_status": "unavailable",
                "error": str(e),
                "confidence_score": 0.0,
                "overall_summary": "NVIDIA review could not be completed. Please rely on the specialist analyses above.",
                "reviewed_by": "NVIDIA Nemotron (offline)",
            },
            "nvidia_review_success": False,
            "errors": [msg],
        }
